import { useState, useEffect } from 'react';
import { inviteService } from '../services/inviteService';
import { Grade } from '../types';

export const usePrCodeGeneration = (schoolId: string, grades: Grade[]) => {
  const [prCodes, setPrCodes] = useState<{ [gradeId: string]: string }>({});
  const [inviteLinks, setInviteLinks] = useState<{ [gradeId: string]: string }>({});
  const [isGeneratingCodes, setIsGeneratingCodes] = useState(false);
  const [autoGeneratedGrades, setAutoGeneratedGrades] = useState<string[]>([]);

  const generatePrCodesAndLinks = async (gradeIds: string[]) => {
    if (gradeIds.length === 0) return {};
    
    setIsGeneratingCodes(true);
    const newPrCodes: { [gradeId: string]: string } = {};
    const newInviteLinks: { [gradeId: string]: string } = {};

    try {
      for (const gradeId of gradeIds) {
        if (prCodes[gradeId]) continue;

        try {
          const prCodeData = await inviteService.generatePrCode(schoolId, gradeId, "enrollment");
          const prCode = prCodeData.code;
          const inviteLink = `https://www.schoolheadoffice.com/school/${schoolId}/enroll?prcode=${prCode}`;
          
          newPrCodes[gradeId] = prCode;
          newInviteLinks[gradeId] = inviteLink;
        } catch (error) {
          console.error(`Error generating PR code for grade ${gradeId}:`, error);
          newPrCodes[gradeId] = "Error generating code";
          newInviteLinks[gradeId] = "Error generating link";
        }
      }

      setPrCodes(prev => ({ ...prev, ...newPrCodes }));
      setInviteLinks(prev => ({ ...prev, ...newInviteLinks }));
      setAutoGeneratedGrades(prev => [...prev, ...gradeIds]);
      
      return newPrCodes;
    } catch (error) {
      console.error('Error in PR code generation process:', error);
      return {};
    } finally {
      setIsGeneratingCodes(false);
    }
  };

  const getPrCodeStatus = (gradeId: string): string => {
    if (isGeneratingCodes && !prCodes[gradeId]) return "🔄 Generating...";
    if (prCodes[gradeId] && prCodes[gradeId] !== "Error generating code") return "✅ Ready";
    if (prCodes[gradeId] === "Error generating code") return "❌ Error";
    return "⏳ Pending";
  };

  // Auto-generate PR codes when grades are loaded
  useEffect(() => {
    if (grades.length > 0 && schoolId) {
      const allGradeIds = grades.map(grade => grade.id);
      generatePrCodesAndLinks(allGradeIds);
    }
  }, [grades, schoolId]);

  return {
    prCodes,
    inviteLinks,
    isGeneratingCodes,
    generatePrCodesAndLinks,
    getPrCodeStatus
  };
};